## 配置端口号
server:
  port: 9002

## 配置数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teaching_training?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL&autoReconnect=true&useSSL=false&failOverReadOnly=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

## 配置 mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cn.teaching.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

## 图片上传路径
file:
  servicePath: http://localhost:9002/files
